export const GET_LEASE = "api/leases";
export const GET_LEASE_INSTALLMENT = "api/lease-rent-installments/";
export const GET_LANDLORD ="api/landlords/";
export const GET_TENANTS= "api/tenants/";
export const GET_SOURCE = "api/sources";
export const GET_PROPERTY_TYPES= "api/property-types";
export const GET_PROPERTY_UNITS= "api/property-units";
export const GET_PROPERTY_LIST= "api/properties";
export const GET_PROPERTY_INVENTORY="api/inventories";